### ISSUE TITLE
Admin login timeout is too short

### ISSUE THREAD

**Issue by NewAllen** [tylerjuniorcollege/brm-manager#47]
Please make the admin login timeout at least 24 hours.

**Comment by duanejeffers** [comment]
So, this is an issue with the server. The timeout for sessions on the server was based on the current browser activity. When the browser is closed, then the PHP session is closed. So, I went ahead and updated the server configuration to have the sessions have a hard timeout of 24 hours. Admins won't have any sort of soft-timeout (where the code determines the session length and not the server), but regular users still have 30 mins to keep active or they will have to login again.
